version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/app
    command: uv run python -m auto_task_manager.main
volumes:
  postgres_data:
